# Generated by Django 5.2.4 on 2025-07-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_status'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursename'),
        ),
    ]
