# Generated by Django 5.2.4 on 2025-07-23 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_month', models.IntegerField(blank=True, null=True)),
                ('weeks', models.IntegerField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('level', models.CharField(choices=[('bootcamp', 'Bootcamp'), ('standard', 'standard'), ('online', 'Online')], max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('intro_video_url', models.CharField(blank=True, help_text='Tanishtiruvchi video uchun YouTube havolasi', max_length=400, null=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': 'Course Name',
                'verbose_name_plural': 'Course Names',
                'db_table': 'course_name',
            },
        ),
        migrations.CreateModel(
            name='AboutCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aboutcourse_set', to='course.course')),
            ],
            options={
                'db_table': 'aboutcourse',
            },
        ),
        migrations.CreateModel(
            name='CourseLearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.TextField(help_text='Kursda o‘rganiladigan asosiy bilim yoki ko‘nikma')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courselearningpoint_set', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graduated_students', models.IntegerField()),
                ('busy', models.IntegerField(blank=True, null=True)),
                ('cheapest_salary', models.IntegerField(blank=True, null=True)),
                ('highest_salary', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics_for_course', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_uuid', models.CharField(help_text='bu yerga hc nima kiritmang!', max_length=16, unique=True)),
                ('certificate_id', models.CharField(help_text='Serifikat id raqamini kiriting', max_length=100, unique=True)),
                ('certificate_url', models.TextField(help_text="Sertifikat joylashgan public urlni qo'ying")),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursename')),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'db_table': 'student_certificates',
            },
        ),
    ]
