# Generated by Django 5.2.4 on 2025-07-23 11:28

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', tinymce.models.HTMLField()),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog',
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(help_text="Blogni bo'limlarga ajratish uchun blog typelarini yarating", max_length=255)),
            ],
            options={
                'verbose_name': 'Blog Type',
                'db_table': 'blogtype',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Blog Images',
                'db_table': 'blog_images',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogtype'),
        ),
    ]
